package com.deezyWallet.walletService.event.inbound;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.deezyWallet.walletService.enums.WalletCommandTypeEnum;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Inbound Kafka event — published by Transaction Service to "wallet.commands" topic.
 * The Wallet Service CONSUMES this — it is the Saga command contract.
 *
 * CRITICAL CONTRACT RULES:
 *
 * 1. @JsonIgnoreProperties(ignoreUnknown = true)
 *    Transaction Service may add new fields in future releases.
 *    The Wallet Service MUST NOT break when it sees unknown fields.
 *    This annotation + Jackson's FAIL_ON_UNKNOWN_PROPERTIES=false (JacksonConfig)
 *    are both set as defense-in-depth.
 *
 * 2. @NoArgsConstructor
 *    Jackson requires a no-arg constructor for deserialisation.
 *    Without it: "Cannot construct instance of WalletCommandEvent" at runtime.
 *    @Builder requires @AllArgsConstructor — both must be present together.
 *
 * 3. All fields are nullable-tolerant (no @NotNull here)
 *    Validation happens inside TransactionEventConsumer AFTER deserialisation.
 *    If we put @NotNull here, Jackson's validation would swallow the message
 *    before we can route it to the DLQ with context.
 *
 * 4. eventId is the Saga correlation ID
 *    Carried through every event in the chain for distributed tracing.
 *    Logged at every step — allows full Saga replay reconstruction in logs.
 *
 * 5. idempotencyKey ≠ eventId
 *    eventId: identifies THIS specific event instance (for dedup at event bus level)
 *    idempotencyKey: identifies the business operation (stored in wallet_transactions)
 *    A retried Saga step has a NEW eventId but the SAME idempotencyKey.
 *    Wallet Service uses idempotencyKey to detect duplicate processing.
 *    eventId is only used for logging/tracing.
 */
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class WalletCommandEvent {

	/** Unique ID of this event instance. Used for tracing, not idempotency. */
	private String            eventId;

	/**
	 * The operation to perform.
	 * DEBIT_CMD, CREDIT_CMD, BLOCK_CMD, UNBLOCK_CMD
	 * Drives the switch in TransactionEventConsumer.
	 */
	private WalletCommandTypeEnum commandType;

	/** Target wallet UUID. Always the wallet being operated on. */
	private String            walletId;

	/** Amount to debit / credit / block / unblock. Always positive. */
	private BigDecimal        amount;

	/**
	 * Business-level dedup key — UUID generated by Transaction Service.
	 * Format: UUID v4, e.g. "550e8400-e29b-41d4-a716-446655440000"
	 * Stored in wallet_transactions.idempotency_key on success.
	 * If seen again → operation is skipped, existing record returned.
	 */
	private String            idempotencyKey;

	/**
	 * Transaction Service's global transaction reference.
	 * Stored in wallet_transactions.reference_id.
	 * Used for cross-service tracing and customer support lookups.
	 * Format: "TXN-YYYYMMDD-XXXXXXXX"
	 */
	private String            transactionRef;

	/** Description shown to user in transaction history. */
	private String            description;

	/** JSON string — flexible metadata bag. Passed through to WalletTransaction. */
	private String            metadata;

	/** When this command was created by Transaction Service. For audit trail. */
	private LocalDateTime     occurredAt;
}
